### ISSUE TITLE
Add support for Travis CI

### ISSUE THREAD

**Issue by jlmorgan** [jlmorgan/node-lodash-extras#3]
Reference example:

```yaml
language: node_js
node_js:
  - "6.0.0"
  - "5.0.0"
  - "4.0.0"
script:
  - npm run build
```
